# Generated by Django 3.1.7 on 2021-03-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210302_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='owner',
        ),
    ]
