# Generated by Django 3.1.7 on 2021-03-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_draft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
