# Generated by Django 3.1.7 on 2021-03-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_delete_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phasechoices',
            field=models.CharField(choices=[('DR', 'Draft'), ('SU', 'Submitted'), ('PU', 'Published'), ('AR', 'Archived'), ('RE', 'Rejected')], default='DR', max_length=2, null=True),
        ),
    ]
